// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:diliow/features/history/domain/decision_record.dart';
import 'package:diliow/features/saved_lists/domain/saved_list.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DecisionModeAdapter());
    registerAdapter(DecisionRecordAdapter());
    registerAdapter(SavedListAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DecisionModeAdapter());
    registerAdapter(DecisionRecordAdapter());
    registerAdapter(SavedListAdapter());
  }
}
